server:
  port: 8090

spring:
  application:
    name: svc-inventory
  data:
    mongodb:
      uri: ${MONGOURI}
  config:
    import: optional:configserver:http://localhost:/8888

eureka:
  instance:
    virtual-host-name: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
