server:
  port: 0

spring:
  application:
    name: auth-service

eureka:
  client:
    enabled: false
  instance:
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0