server:
  port: 8090

spring:
  application:
    name: inv-service
  data:
    mongodb:
      uri: ${MONGOURI}
  security:
    api:
      key: ${API_KEY}
    admin:
      mail: ${ADMIN_MAIL}
      password: ${ADMIN_PASSWORD}

eureka:
  client:
    enabled: false
  instance:
    enabled: false
