server:
  port: 0

spring:
  application:
    name: not-service
  rabbitmq:
    host: 192.168.1.2
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchange:
    name: ${RABBIT_EXCHANGE_NAME}
  inventory:
    queue:
      string:
        name: ${RABBIT_INVENTORY_QUEUE_STRING_NAME}
      json:
        name: ${RABBIT_INVENTORY_QUEUE_JSON_NAME}
    routing:
      key:
        string:
          name: ${RABBIT_INVENTORY_STRING_ROUTING_KEY}
        json:
          name: ${RABBIT_INVENTORY_JSON_ROUTING_KEY}

  order:
    queue:
      name:
    routing:
      key:

