server:
  port: 0

spring:
  security:
    api:
      key: ${API_KEY}
  application:
    name: us-service
  data:
    mongodb:
      uri: ${MONGOURI_USERS}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchange:
    name: ${RABBIT_EXCHANGE_NAME}
  inventory:
    queue:
      string:
        name: ${RABBIT_INVENTORY_QUEUE_STRING_NAME}
      json:
        name: ${RABBIT_INVENTORY_QUEUE_JSON_NAME}
    routing:
      key:
        string:
          name: ${RABBIT_INVENTORY_STRING_ROUTING_KEY}
        json:
          name: ${RABBIT_INVENTORY_JSON_ROUTING_KEY}
