server:
  port: 0

spring:
  application:
    name: ord-service
  data:
    mongodb:
      uri: ${MONGOURI_ORDERS}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
