server:
  port: 0

spring:
  application:
    name: ord-service
  data:
    mongodb:
      uri: ${MONGOURI_ORDERS}
  security:
    api:
      key: ${API_KEY}
    admin:
      mail: ${ADMIN_MAIL}
      password: ${ADMIN_PASSWORD}

eureka:
  client:
    enabled: false
  instance:
    enabled: false
