server:
  port: 0

spring:
  application:
    name: ord-service
  data:
    mongodb:
      uri: ${MONGOURI_ORDERS}
  security:
    api:
      key: ${API_KEY}
    admin:
      mail: ${ADMIN_MAIL}
      password: ${ADMIN_PASSWORD}

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
