server:
  port: 0

spring:
  application:
    name: us-service
  data:
    mongodb:
      uri: ${MONGOURI_USERS}
  security:
    api:
      key: ${API_KEY}

eureka:
  client:
    enabled: false
  instance:
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0
