server:
  port: 8091

spring:
  application:
    name: us-service
  data:
    mongodb:
      uri: ${MONGOURI}
  config:
    import: optional:configserver:http://localhost:/8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
