trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  mavenOptions: '-Xmx2g'

resources:
  repositories:
    - repository: self
      type: git

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'us-service/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildUsService

  - task: Maven@3
    inputs:
      mavenPomFile: 'auth-service/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildAuthService

  - task: Maven@3
    inputs:
      mavenPomFile: 'inv-service/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildInvService

  - task: Maven@3
    inputs:
      mavenPomFile: 'not-service/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildNotService

  - task: Maven@3
    inputs:
      mavenPomFile: 'ord-service/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildOrdService

  - task: Maven@3
    inputs:
      mavenPomFile: 'rep-service/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildRepService

  - task: Maven@3
    inputs:
      mavenPomFile: 'api-gateway/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildApiGateway

  - task: Maven@3
    inputs:
      mavenPomFile: 'config-server/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildConfigServer

  - task: Maven@3
    inputs:
      mavenPomFile: 'eureka-service/pom.xml'
      goals: 'clean package'
      options: '$(mavenOptions)'
    name: BuildEurekaDiscoveryClient

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/us-service/target'
      artifactName: 'us-service'
    name: PublishUsServiceArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/auth-service/target'
      artifactName: 'auth-service'
    name: PublishAuthServiceArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/inv-service/target'
      artifactName: 'inv-service'
    name: PublishInvServiceArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/not-service/target'
      artifactName: 'not-service'
    name: PublishNotServiceArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/ord-service/target'
      artifactName: 'ord-service'
    name: PublishOrdServiceArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/rep-service/target'
      artifactName: 'rep-service'
    name: PublishRepServiceArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/api-gateway/target'
      artifactName: 'api-gateway'
    name: PublishApiGatewayArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/config-server/target'
      artifactName: 'config-server'
    name: PublishConfigServerArtifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(System.DefaultWorkingDirectory)/eureka-service/target'
      artifactName: 'eureka-service'
    name: PublishEurekaServiceArtifacts
