spring:
  profiles:
    active: @profileActive@
  application:
    name: us-service
  config:
    import: optional:configserver:https://config-server.icywater-e8b8ee0a.eastus.azurecontainerapps.io

#logging:
#  level:
#    root: debug
#    org.springframework.web: debug
#    com.cesar.usservice: debug
