spring:
  profiles:
    active: @profileActive@
  application:
    name: us-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: debug
    org.springframework.web: debug
    com.cesar.usservice: debug
