server:
  port: 8090

spring:
  application:
    name: svc-inventory
  data:
    mongodb:
      uri: mongodb+srv://cesar:cesar123456@cluster0.yealtoe.mongodb.net/inventory-system?retryWrites=true&w=majority&appName=Cluster0
  config:
    import: optional:configserver:http://localhost:/8888

eureka:
  instance:
    virtual-host-name: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
