spring:
  profiles:
    active: @profileActive@
  application:
    name: eureka-service
  config:
    import: optional:configserver:https://config-server.icywater-e8b8ee0a.eastus.azurecontainerapps.io
