server:
  port: 8888

spring:
  profiles:
    active: native # We can configure this to use other profiles
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration
